version: 2.1

workflows:
  version: 2
  build:
    jobs:
      - build

jobs:
  build:
    working_directory: ~/SimpleApplication
    docker:
      - image: cimg/node:20.11
    steps:
      - checkout
      - run:
          name: install dependencies
          command: npm install
